import fs from 'fs';
import { LogManager } from '../LogManager';

export const kValidators: {[key: string]: {name: string}} = {
    'he1iusunGwqrNtafDtLdhsUQDFvo13z9sUa36PauBtk': {name: `Helius`},
    'CvSb7wdQAFpHuSpTYTJnX5SYH4hCfQ9VuGnqrKaKwycB': {name: `Galaxy`},
    '6D2jqw9hyVCpppZexquxa74Fn33rJzzBx38T58VucHx9': {name: `Coinbase 02`},
    'CcaHc2L43ZWjwCHART3oZoJvHLAe9hzT2DJNUpBzoTN1': {name: `Figment`},
    '26pV97Ce83ZQ6Kz9XT4td8tdoUFPTng8Fb8gPyc53dJx': {name: `Ledger by Figment`},
    'FKsC411dik9ktS6xPADxs4Fk2SCENvAiuccQHLAPndvk': {name: `P2P.org`},
    '9QU2QSxhb24FUX3Tu2FpczXjpK3VYrvRudywSZaM29mF': {name: `Everstake`},
    '3N7s9zXMZ4QqvHQR15t5GNHyqc89KduzMP7423eWiD5g': {name: `binance staking`},
    'CatzoSMUkTRidT5DwBxAC2pEtnwMBTpkCepHkFgZDiqb': {name: `Jupiter Validator [0% Commission + 100% MEV Kickback]`},
    'Ak5BJzQe2R8qFuyYmaAFPjXuD7XPux3ZNTv52D7rfiqR': {name: `Twinstake`},
    'DumiCKHVqoCQKD8roLApzR5Fit8qGV5fVQsJV9sTZk4a': {name: `Staking Facilities | MEV 🔥`},
    'J1to2NAwajc8hD6E6kujdQiPn1Bbt2mGKKZLY9kSQKdB': {name: `Jito2`},
    'DdCNGDpP7qMgoAy6paFzhhak2EeyCZcgjH7ak5u5v28m': {name: `Kiln`},
    'J1to1yufRnoWn81KYg1XkTWzmKjnYSnmE2VY8DGUJ9Qv': {name: `Jito1`},
    'KRAKEnMdmT4EfM8ykTFH6yLoCd5vNLcQvJwF66Y2dag': {name: `Kraken`},
    '8Pep3GmYiijRALqrMKpez92cxvF4YPTzoZg83uXh14pW': {name: `private`},
    'GvZEwtCHZ7YtCkQCaLRVEXsyVvQkRDhJhQgB6akPme1e': {name: `0% Fee >> #1 🥇 | melea One`},
    'HxRrsnbc6K8CdEo3LCTrSUkFaDDxv9BdJsTDzBKnUVWH': {name: `StakeHaus - 0% Fee on Rewards/MEV`},
    '3Ty8DYNBkK237zPvACti83EJYGxDcMcoDMCou5r3eV5Q': {name: `SOL Community`},
    'GHViLgbrJdZDPb6sphRbeuPNM9cmjsFuGWzrTF1sKF5n': {name: `Upbit Staking`},
    '6aow5rTURdbhbeMDrFrbP2GR5vZjMEhktEy87iH1VGPs': {name: `Luganodes`},
    'BLADE1qNA1uNjRgER6DtUFf7FU3c1TWLLdpPeEcKatZ2': {name: `Shinobi Systems 🚀 stakeview.app`},
    'EXhYxF25PJEHb3v5G1HY8Jn8Jm7bRjJtaxEghGrUuhQw': {name: `Solflare`},
    'CertusDeBmqN8ZawdkxK5kFGMwBXdudvWHYwtNgNhvLu': {name: `Asymmetric Research`},
    'beefKGBWeSpHzYBHZXwp5So7wdQGX6mu4ZHCsH3uTar': {name: `Coinbase`},
    'Cat8oWQiFfrR3c7BcceTYcpnYCzSWfCPjMXT7mfHXvEP': {name: `HashKey Cloud`},
    'F5b1wSUtpaYDnpjLQonCZC7iyFvizLcNqTactZbwSEXK': {name: `AG 0% fee + ALL MEV profit share`},
    '51JBzSTU5rAM8gLAVQKgp4WoZerQcSqWC7BitBzgUNAm': {name: `Staked`},
    'GE6atKoWiQ2pt3zL7N13pjNHjdLVys8LinG8qeJLcAiL': {name: `Laine ❤️ stakewiz.com`},
    'DQ7D6ZRtKbBSxCcAunEkoTzQhCBKLPdzTjPRRnM6wo1f': {name: `StakeWolf`},
    '9GJmEHGom9eWo4np4L5vC6b6ri1Df2xN8KFoWixvD1Bs': {name: `Block Logic +MEV +Triton`},
    'DMSuZcavta8L1w1tSiH8bALWjz6Q6KSryGG6m6Az4Qt5': {name: `Lion3d | 0% Forever`},
    'mrgn4t2JabSgvGnrCaHXMvz8ocr4F52scsxJnkQMQsQ': {name: `mrgn4`},
    'mrgn6ETrBDM8mjjYN8rbVwFqVwF8z6rtmvGLbdGuVUU': {name: `mrgn3`},
    '7KVnUL45FH4N8Z7x1dnvJ7GzMx12cs81mS26mHzNjQPN': {name: `PoH PoS`},
    'RBFvvcGPBpgkBYmJGsphoDQJD8sszSuorM7TorWm12Y': {name: `RockawayX Infra`},
    'Chorus6Kis8tFHA7AowrPMcRJk3LbApHTYpgSNXzY5KE': {name: `Chorus One`},
    'AS3nKBQfKs8fJ8ncyHrdvo4FDT6S8HMRhD75JjCcyr1t': {name: `Overclock`},
    'EARNynHRWg6GfyJCmrrizcZxARB3HVzcaasvNa8kBS72': {name: `Solana Compass 🧭 Solana For The People`},
    'DsiG71AvUHUEo9rMMHqM9NAWQ6ptguRAHyot6wGzLJjx': {name: `Pumpkin's Pool 🐈 Supports Animal Welfare ❤️`},
    'FQwewNXahV7MiZcLpY6p1xhUs2acVGQ3U5Xxc7FzV571': {name: `Blockdaemon 🧱👿 Validator`},
    '6F5xdRXh2W3B2vhte12VG79JVUkUSLYrHydGX1SAadfZ': {name: `Allnodes ⚡️ 0% fee`},
    'Haz7b47sZBpxh9SwggGndN3fAyNQ1S949BPdxWXS3ab6': {name: `Temporal Emerald`},
    'GNZ1PAAS33davY4Q1BMEpZEpVBtRtGvSpcTH5wYVkkVt': {name: `Stakeconomy 🚀 Jito MEV + Triton.One`},
    'GREEDkpTvpKzcGvBu9qd36yk6BfjTWPShB67gLWuixMv': {name: `GREED Academy - funding education`},
    'QUANT7qKUEW4PS4eP9jq4K35rDHpgWkWcgjbW1CwnGJ': {name: `Quantum | 0% >> 8M`},
    '7S9dHgoeMYvtShTjEC3x5D3THRDQz123WVGPseZsm3hm': {name: `Rocket`},
    '7opSZGmevWhRDyLt5Wu38FZFjUyredGmMki4DNmxDnjd': {name: `Alpha Pro | High APY🚀 100% Reliable ⭐ VIP Services`},
    '5sMmkL4BXjU6vZXQxE3RquH2CR8v8Zbfi1EAAFxLfxMx': {name: `Alpha`},
    '5orRi4tMEGneZ9U2y381JnBEnsqFJDBSNQLhBn98Bkcv': {name: `Quatro`},
    '3tUZu4CkwMLwYdosoGc85n48VgDMyxZVkL1VUJc7DrxW': {name: `Flash`},
    'voteRnv6PBzmiGP8NicWtQiqEJTwKKq2SxtqtdLUJjd': {name: `DimAn`},
    '8uEgdseqbUrDLfmHbUpTHoH1LLRxeViYDk7K6NdXKRYM': {name: `Hamsa`},
    'juicQdAnksqZ5Yb8NQwCLjLWhykvXGktxnQCDvMe6Nx': {name: `Juicy Stake`},
    'Pond1QyT1sQtiru3fi9G5LGaLRGeUpJKR1a2gdbq2u4': {name: `Leapfrog 🐸 topvalidators.app`},
    'Va1idkzkB6LEmVFmxWbWU8Ao9qehC62Tjmf68L3uYKj': {name: `validator.com`},
    '8zHJtME22tiY3UsSHtDJXo2J8hUfwikBxXNbVqQzA92r': {name: `Bella2.0`},
    'CogentC52e7kktFfWHwsqSmr8LiS1yAtfqhHcftCPcBJ': {name: `Cogent Crypto ⚙️ CogentCrypto.io`},
    '2tucttroqFNXsrYeMBQ8LfzKNfgwT2rHBzAF6RzbbHEp': {name: `OKX Earn`},
    'edu1fZt5i82cFm6ujUoyXLMdujWxZyWYC8fkydWHRNT': {name: `LowFeeValidation + MEV TOP PERFORMANCE`},
    'BxFf75Vtzro2Hy3coFHKxFMZo5au8W7J8BmLC3gCMotU': {name: `Chainode Tech & MEV(0% Fee)`},
    'oRAnGeU5h8h2UkvbfnE5cjXnnAa4rBoaxmS4kbFymSe': {name: `Orangefin Ventures`},
    'EwsDhgfbT6H4FRC7AHdhXNBxfBSbWCbDfknrw6g5Dph6': {name: `Unit 410`},
    'B6nDYYLc2iwYqY3zdmavMmU9GjUL2hf79MkufviM2bXv': {name: `Mad Validator`},
    'Ev3gPXRo6TJeQ2QhxfqWFoasdoGbmDytYvJbUabEHfLf': {name: `Chive 🌱 0% Fee Forever + MEV`},
    'mintrNtxN3PhAB45Pt41XqyKghTTpqcoBkQTZqh96iR': {name: `Hanabi Staking 🎆 | Staking Champions`},
    'SmithX2hngQMZXVN36C6TsyjthTU3YnsALAs1MaDghV': {name: `Blocksmith`},
    '8yPiZWMNYMhEqTmPSRc6LsWLFC8pewYEzmgc5kRCLTrZ': {name: `Limitless Systems`},
    'mrgn2vsZ5EJ8YEfAMNPXmRux7th9cNfBasQ1JJvVwPn': {name: `mrgn2`},
    'EcLPNfLFgCkbcTuvdeQ85pnQMgAfBDqi2dkoNVPrSyr5': {name: `Bitcoin Suisse`},
    'StepeLdhJ2znRjHcZdjwMWsC4nTRURNKQY8Nca82LJp': {name: `Step Finance`},
    '7emL18Bnve7wbYE9Az7vYJjikxN6YPU81igf6rVU5FN8': {name: `Temporal Topaz`},
    'J1to3PQfXidUUhprQWgdKkQAMWPJAEqSJ7amkBDE9qhF': {name: `BONK - Powered by Jito`},
    'CAf8jfgqhia5VNrEF4A7Y9VLD3numMq9DVSceq7cPhNY': {name: `Chainflow`},
    'DriFTm3wM9ugxhCA1K3wVQMSdC4Dv4LNmyZMmZiuHRpp': {name: `Drift`},
    'RNXpSdqrJL6eoLrbW69Q9qsFviEwRpfFfk3HiRRRohq': {name: `The Gods Themselves`},
    '4PsiLMyoUQ7QRn1FFiFCvej4hsUTFzfvJnyN4bj1tmSN': {name: `Stakin`},
    'J2nUHEAgZFRyuJbFjdqPrAa9gyWDuc7hErtDQHPhsYRp': {name: `Phantom Validator`},
    '7VGU4ZwR1e1AFekqbqv2gvjeg47e1PwMPm4BfLt6rxNk': {name: `stakefish 🐟`},
    '696fkFqwiLxsDG8Jr5MvU9kvGm9uuMuTPh3rn3ybRNQm': {name: `BlockStake Labs | 0% Fee`},
    '7K8DVxtNJGnMtUY1CQJT5jcs8sFGSZTDiG7kowvFpECh': {name: `SolanaHub`},
    '39xF5qkfK5HBaG4Hkq6bjumUB2k4B5ozEAmfZoobhUVw': {name: `kerak69 💥0% fee + Jito MEV💥`},
    '9sWYTuuR4s12Q4SuSfo5CfWaFggQwA6Z8pf8dWowN5rk': {name: `Ubik Capital - 0% Fee, MEV`},
    '6hZL2FZim27WkQccMfygvvXH2eow5u3wR6XUJHbMoeWP': {name: `Xandeum Labs 0% fee + MEV = 🔥APY %`},
    'D8aGMETy3q6ymADJs7YS81QY2qTQmptVox3iCfGDgSTA': {name: `SolTA`},
    'BeachiopjxQxL7CaHNSZsynApiZCKx9QFVtcWNz3jDBo': {name: `Solana Beach Validator`},
    'D3QPJm7BDzzPeRG51YZSEz3LfV7GvFNu9NkcibzURxuj': {name: `StaRKe`},
    'FPjq7vB2V3TiseJJSPsp47UWSfT4AwvKjiU7GEro7bX9': {name: `Aspis 🛡 +MEV`},
    '2Gife8andd4BkEbT5CncpriPxmQYqbspDh8cXkN6RUSH': {name: `RushChain`},
    'AjdEzodq5LpRA63AtQaiHyTLDfjTkr6csrtYWiSDPjaK': {name: `IMPULSE⚡️`},
    'DUCKsGEPEdNv9QeskPNwoJdWgAXjxUFrkNDEKjAnLWyY': {name: `ARCHER 0% commission + MEV`},
    'HFLsfstZkJeWDgVEA5fmXeea876Ad9f1VxrbXk386bBY': {name: `Consensus 🤝`},
    '76nwV8zz8tLz97SBRXH6uwHvgHXtqJDLQfF66jZhQ857': {name: `Forbole`},
    '4v2os15BGgAnqiy76YvPmAywp5xKh9jfBPfnQGzUVc9c': {name: `darko | Platinum validator`},
    '5EYp3kCdMLq52vzZ4ucsVyYaaxQe5MKTquxahjXpcShS': {name: `Mango Validator`},
    'yrfQfUfsZechz1zqQyTRRz43czTZQidcrm4SNVWiDPi': {name: `Sharpei`},
    'eondcw2upjH14EuvBzmn6HfGEGo8t9hG9JbXtPj6cym': {name: `EONpool`},
    'GB44NXtM7zGm6QnzQjzHZcRKSswkJbox8aJsKiXGbFJr': {name: `Rustiq Technology`},
    '2w4dcnbJDcGrAh4CFAYYpAaEJiUB2q1rFMGByBuB5Cqz': {name: `Vlaber01`},
    'Cn9bZCGSYN57GsTfJ5YLCy8HMejHZqrBQkv99eusJtEH': {name: `cesar`},
    'CzmqDuqEpfnkptuLAcikmJrhCnhFXo8aUBj6Rto1SPAc': {name: `MARGUS.ONE 💎 0% fee +MEV!`},
    'DPhzpiNGU9C6576uLsNSHmdi2AxwxpjMsRdh2iVC4TPh': {name: `SoLyrae`},
    '1Dadio3JRvpEjY6iSmXmhbGy9RiU8Nxh2GmoVbNusbE': {name: `1Dad 🚀 0% Fee + MEV`},
    'FahWJg2PkphJaMUUCzdYhXkD5NngUuuFRFD3YCE3BSwb': {name: `Vault X | 0% fee +MEV`},
    '5K8qgC9nHzKHSSyo9fKLsMfYmavYdMgEaYx86cMmVKVv': {name: `Solana Community Administrator Node`},
    'EdGevanAjM8a6Gg9KxBVrmVdZAUGAZ9xaVd7t9R4H2x': {name: `Edgevana`},
    'HwcVgFSgmfeeF7zGFUBLoVA8Hpx8rtwyfCrJ1npBaSVC': {name: `Solya`},
    'DimavhUqvCpWjUZqSFZGLqBiUVUYQ5jZEaCHutKKVs45': {name: `VolanD`},
    '5HScvYkTWL9iojhPv26xK7GqB7oBsj9A2qHCeNRFmdyG': {name: `ex1arey 💫 0% fee + MEV!`},
    'EKUh585fWD7LeDRHgmYd9EXpQnY6KNbNAhyBi3FuVw6Y': {name: `Dependable Solana Validator +MEV`},
    '6W8yrMwtDU5G6ErazhZHfLjqZV8cMvajpSRGYgrZ3d4v': {name: `Legends`},
    '49DJjUX3cwFvaZD5rCAwubiz7qdRWDez9xmB381XdHru': {name: `Staker Space`},
    '9xEFsHZt2mbuGQjtVGABxpeQiNeDvj54pfsJrrrUUev6': {name: `Ereborus ⚔️  MEV`},
    '7PmWxxiTneGteGxEYvzj5pGDVMQ4nuN9DfUypEXmaA8o': {name: `Syncnode`},
    '3r5ZXC1yFqMmk8VwDdUJbEdPmZ8KZvEkzd5ThEYRetTk': {name: `Vnode`},
    'A7uqmajxP3NdzbYDXiGQRGTL8d3dZ5pjS4kR9NTZcxtg': {name: `L0vd 0% fee +MEV`},
    'BWkvytz3MAiLkUbMuYK5yV1VYThbBYYQYG3gdef8NLw5': {name: `SerGo`},
    'B1w6SZcyvjyp6zEyStcc8u9AxXAh2AbYvNzMmP9rRKE9': {name: `Nordic Staking 0% fee top APY +MEV`},
    'FiijvR2ibXEHaFqB127CxrL3vSj19K2Kx1jf2RbK4BWS': {name: `Trust Nodes`},
    '37BPVW1Ne1XHrzK15xguAS2BTdobVfThDzTE2mv8SsnJ': {name: `InfStones`},
    'Ac1beBKixfNdrTAac7GRaTsJTxLyvgGvJjvy4qQfvyfc': {name: `Stronghold 3% Fee + MEV`},
    'NoRDTy8jpkpjPR7yxahVdoEUPngbojPhFU5jb8TtY4m': {name: `nordstar ⭐ reliable staking +MEV`},
    '5mSBnz3zNSVzXQHxBmrTLESynukH2JHVcCN14GHtVsWD': {name: `Asteroid staking`},
    '5iJDEVRi1nMLwKAWhYbEokZnvBAe15rgFaHGkggVEP9z': {name: `Stardust Staking - 0% fee forever`},
    '6SmEcnuXJ3ZYqJWTqCoPQMhfvey6PfWb1LebLzoH3f7m': {name: `GrandpaStake`},
    'GrefCNn5jSbcWv3uiervqZiCC87F8oX7PXz9LEBiog6s': {name: `TruFin`},
    'H7JJ6aE73ufbUuDCZSQMxguQsj28XHe4VQyMk2hsVGoo': {name: `GOOSE`},
    'Rash24BXgUyy65JJ5KBzpYLrj3pyCqEMEixLVimTcDp': {name: `Stakerrash`},
    '2ayMCC4aizr8RGg5ptXYqu8uoxW1whNek1hE1zaAd58z': {name: `Lifinity Protocol`},
    'GQ8DSRSNCFGEdCEwc6em1ma18qSPc5cXCSDnSPSznWBP': {name: `Dreik-Steak 0% fee + MEV`},
    'GA2t11gJcmuZ4y7pShTzgYDkxVaJaVQJqkVUqojhPPsT': {name: `SolBrothers`},
    '3Xn3K5zeTzs4sURj1PCRaF6rvFg2hPgT49B4SiM998f7': {name: `NuFi`},
    '34yvUa2fxfm2tUqxFEj9PHrVNwCcdzd51eo9hntWpZRs': {name: `Aurora Validator`},
    '48oxpSHQkM4sdXUY9NQ8KnEtebzZbyk8uUT7JRdVQNuf': {name: `✨ lux8.net ✨`},
    'tri1cHBy47fPyhCvrCf6FnR7Mz6XdSoSBah2FsZVQeT': {name: `Trillium: Stake, Earn, and Fuel Solana!`},
    'Luck3DN3HhkV6oc7rPQ1hYGgU3b5AhdKW9o1ob6AyU9': {name: `Lucky Stake`},
    'A2MtELFxn9wAiUrobrZ6vsypQtGHdH3ZesEnvAogvuFZ': {name: `☀️ SolaraZ ☀️ +MEV`},
    'Ehdn9LdjTAURQSMoDPERXLehtvzy7QD762wwPkzGT7RS': {name: `SuperteamDE x Staking Facilities | Public Goods Validator`},
    '3zEbnWKibg574DaGC1EA3zLNwBK6MGQxEySUgQWKBaYV': {name: `OHara Nodes`},
    'HAK7iPgQTFwqEzPfVrRDbG5epFdk1dsA9qQexytsDoes': {name: `StakeShip 🛳  Additional rewards`},
    'StakeyJXE1yJbEApBVswHN4JdZXcj7V5MHbzffa4dFp': {name: `Stake.org`},
    '5iZ5PQPy5Z9XDnkfoWPi6nvUgtxWnRFwZ36WaftPuaVM': {name: `Meyerbro +MEV`},
    'i6PZjkPHGYmPfPE8LsJuLn5huZyusXhmysiDiHGPjxb': {name: `MARVEL+MEV!`},
    '6n8taYki7RscA1XW7xGmevLcqj855oSgDgjPe1dZyHfW': {name: `Table Rock Jungle Lodge`},
    '6GoijNiK3JZVAY96ykCfPhcJnrQfrQMLvrQaX5HyMVhu': {name: `byasa mencius`},
    '6JfBwvcz5QUKQJ37BMKTLrf968DDJBtwoZLw19aHwFtQ': {name: `Spectrum Staking +MEV`},
    'punK4RDD3pFbcum79ACHatYPLLE1hr5UNnQVUGNfeyP': {name: `Sol Strategies`},
}

export const kKnownAddresses: {[key: string]: {name: string}} = {
    '96gYZGLnJYVFmbjzopPSU6QiEV5fGqZNyN9nmNhvrZU5': {name: `Jitotip 1`},
    'HFqU5x63VTqvQss8hp11i4wVV8bD44PvwucfZ2bU7gRe': {name: `Jitotip 2`},
    'Cw8CFyM9FkoMi7K7Crf6HNQqf4uEMzpKw6QNghXLvLkY': {name: `Jitotip 3`},
    'ADaUMid9yfUytqMBgopwjb2DTLSokTSzL1zt6iGPaS49': {name: `Jitotip 4`},
    'DfXygSm4jCyNCybVYYK6DwvWqjKee8pbDmJGcLWNDXjh': {name: `Jitotip 5`},
    'ADuUkR4vqLUMWXxW9gh6D6L8pMSawimctcNZ5pGwDcEt': {name: `Jitotip 6`},
    'DttWaMuVvTiduZRnguLF7jNxTgiMBZ1hyAumKUiL2KRL': {name: `Jitotip 7`},
    '3AVi9Tg9Uo68tJfuvoKvqKNWKkC5wPdSSdeBnizKZ6jT': {name: `Jitotip 8`},
    '43DbAvKxhXh1oSxkJSqGosNw3HpBnmsWiak6tB5wpecN': {name: `Backpack Exchange`},
    'LFEEa8RzpbWaFgzPXLJQcGGDYLAeaaBAMp6WWCgxJM3': {name: `Light Treasury`},
    'LFEE8P4pMBPpHzEytWrQHELdNsNM1otnvRzUUoFtX5N': {name: `Light Treasury Dev`},
}

export const kSolscanAddresses: {[key: string]: {name: string}} = {};
export const initSolscanLabels = async () => {
    try {
        const jsonString = fs.readFileSync('src/files/solscan-labels.json', 'utf8');
        const labels: {
            program: {[key: string]: string},
            address: {[key: string]: string},
            hacker: {[key: string]: string},
            trust_token: {[key: string]: string},
        } = JSON.parse(jsonString);

        const lists = [labels.program, labels.address, labels.hacker];
        for (const list of lists) {
            for (const address in list) {
                if (Object.prototype.hasOwnProperty.call(list, address)) {
                    const title = list[address];
                    kSolscanAddresses[address] = {name: title};
                }
            }                
        }
    }
    catch (error) {
        LogManager.error('initSolscanLabels', error);
    }
}